module.exports = {

    CONSTANTS: {
        /* CODIGOS DE ERROR CON LA BASE DE DATOS */
        PROTOCOL_CONNECTION_LOST: 'PROTOCOL_CONNECTION_LOST',
        ER_CON_COUNT_ERROR: 'ER_CON_COUNT_ERROR',
        ECONNREFUSED:"ECONNREFUSED",
        ER_ACCES_DENIED_ERROR:"ER_ACCES_DENIED_ERROR"
    }
}